name: Code Quality

on:
  workflow_call:
    inputs:
      slug:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Environment
        uses: SP-Packages/actions/.github/actions/setup-environment@main
        with:
          DEV_DEPENDENCIES: true

      - name: Run LintRC
        run: npx lintrc
        continue-on-error: true

      - name: Run ESLint
        run: npx eslint . --max-warnings=0
        continue-on-error: true

      - name: Run Prettier
        run: npx prettier --check .
        continue-on-error: true

      - name: Run cspell (spell-check)
        run: npx cspell "**/*.{ts,js,json,md}"
        continue-on-error: true

      - name: Run TypeScript
        run: npx tsc --noEmit
        continue-on-error: true

      - name: Run Commitlint
        run: npx commitlint --from=origin/main --to=HEAD --verbose
        continue-on-error: true

      - name: Run Tests
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: cli, core, utils, tests
          verbose: true
          slug: ${{ inputs.slug }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
