name: Code Quality

on:
  workflow_call:
    inputs:
      VERBOSE:
        type: boolean
        default: false
        required: false

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 21]
    steps:
      - name: Setup Environment
        uses: SP-Packages/actions/.github/actions/setup-environment@main
        with:
          FETCH_DEPTH: 0
          SETUP_NODE: true
          INSTALL_DEPENDENCIES: true
          INSTALL_DEV_DEPENDENCIES: true
          NODE_VERSION: ${{ matrix.node }}

      - name: Run LintRC
        run: npx @sp-packages/lintrc ${{ inputs.VERBOSE && '--verbose' || '' }}
