name: Rebase Develop

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  rebase-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch latest changes
        run: |
          git fetch origin main develop

      - name: Rebase develop onto main
        run: |
          git checkout develop
          git rebase origin/main || (git rebase --abort && exit 1)

      - name: Force push develop
        run: |
          git push --force-with-lease origin develop
