name: Semantic Release

on:
  workflow_call:
    inputs:
      DRY_RUN:
        type: boolean
        required: false
        default: false
      PREPARE_DEST_DIR:
        type: boolean
        required: false
        default: false

    secrets:
      GH_TOKEN:
        required: true
      NPM_TOKEN:
        required: false

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: SP-Packages/actions/.github/actions/setup-environment@main
        with:
          FETCH_DEPTH: 0
          SETUP_NODE: true
          INSTALL_DEPENDENCIES: true
          INSTALL_DEV_DEPENDENCIES: true

      - name: Run Build Script
        if: ${{ inputs.PREPARE_DEST_DIR == 'true' }}
        run: |
          npm run build
          zip -r dist.zip dist/
        shell: bash

      - name: Run Semantic Release
        run: npx semantic-release --dry-run=${{ inputs.DRY_RUN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
